name: Update Chocolatey Package

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  update-package:
    runs-on: windows-latest
    steps:
      - name: Checkout repository into 'uv' directory
        uses: actions/checkout@v4
        with:
          path: uv  # Check out the repository into the 'uv' directory

      - name: Set up Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install AU
        run: choco install chocolatey-au -y

      - name: Update package
        id: update
        run: |
          cd uv  # Change to the 'uv' directory
          $output = .\update.ps1 | Out-String  # Capture the output as a string
          Write-Output $output  # Display the output in the workflow logs
          $version = ($output -split "`n")[-2].Trim()
          echo "version=$version" >> $env:GITHUB_OUTPUT  # Set the version output
        env:
          github_api_key: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Push package to Chocolatey
        run: |
          cd uv  # Change to the 'uv' directory
          choco push "uv.${{ steps.update.outputs.version }}.nupkg" --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCO_API_KEY }}
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}

      - name: Commit changes
        run: |
          cd uv  # Change to the 'uv' directory
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update package to version ${{ steps.update.outputs.version }}" -a || echo "No changes to commit"
          git push
